# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: a700e964b95473caceb2974206b600566c98bac72daf731d9157564e26cf64a9
# Generated: 2026-07-15T18:51:55Z

from __future__ import annotations

from typing import Any, Callable, Iterator, TypeVar

T = TypeVar("T")


def paginate(fetch_page: Callable[..., Any], size: int = 100) -> Iterator[Any]:
    page = 1
    while True:
        result = fetch_page(page=page, size=size)
        yield from result.items
        if page * size >= result.total:
            break
        page += 1
