# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 197bcf63df9f7ac0369a0ccad308a36b1987c7342bcaeb19c0218369f3bf2fe4
# Generated: 2026-07-09T09:47:53Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .role_binding import RoleBinding, RoleBindingList

if TYPE_CHECKING:
    from .client import AmbientClient


class RoleBindingAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> RoleBinding:
        resp = self._client._request("POST", "/role_bindings", json=data)
        return RoleBinding.from_dict(resp)

    def get(self, resource_id: str) -> RoleBinding:
        resp = self._client._request("GET", f"/role_bindings/{resource_id}")
        return RoleBinding.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> RoleBindingList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/role_bindings", params=params)
        return RoleBindingList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> RoleBinding:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/role_bindings/{resource_id}", json=data)
        return RoleBinding.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"/role_bindings/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[RoleBinding]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
