// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 197bcf63df9f7ac0369a0ccad308a36b1987c7342bcaeb19c0218369f3bf2fe4
// Generated: 2026-07-09T09:47:53Z

import type { ObjectReference, ListMeta } from './base';

export type Policy = ObjectReference & {
  annotations: string;
  labels: string;
  name: string;
  namespace: string;
  project_id: string;
  spec: string;
};

export type PolicyList = ListMeta & {
  items: Policy[];
};

export type PolicyCreateRequest = {
  annotations?: string;
  labels?: string;
  name: string;
  namespace?: string;
  project_id: string;
  spec?: string;
};

export type PolicyPatchRequest = {
  annotations?: string;
  labels?: string;
  name?: string;
  namespace?: string;
  spec?: string;
};

export class PolicyBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  namespace(value: string): this {
    this.data['namespace'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  spec(value: string): this {
    this.data['spec'] = value;
    return this;
  }

  build(): PolicyCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as PolicyCreateRequest;
  }
}

export class PolicyPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  namespace(value: string): this {
    this.data['namespace'] = value;
    return this;
  }

  spec(value: string): this {
    this.data['spec'] = value;
    return this;
  }

  build(): PolicyPatchRequest {
    return this.data as PolicyPatchRequest;
  }
}
