// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 197bcf63df9f7ac0369a0ccad308a36b1987c7342bcaeb19c0218369f3bf2fe4
// Generated: 2026-07-09T09:47:53Z

import type { ObjectReference, ListMeta } from './base';

export type Provider = ObjectReference & {
  annotations: string;
  labels: string;
  name: string;
  namespace: string;
  project_id: string;
  secret: string;
  type: string;
};

export type ProviderList = ListMeta & {
  items: Provider[];
};

export type ProviderCreateRequest = {
  annotations?: string;
  labels?: string;
  name: string;
  namespace?: string;
  project_id: string;
  secret?: string;
  type?: string;
};

export type ProviderPatchRequest = {
  annotations?: string;
  labels?: string;
  name?: string;
  namespace?: string;
  secret?: string;
  type?: string;
};

export class ProviderBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  namespace(value: string): this {
    this.data['namespace'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  secret(value: string): this {
    this.data['secret'] = value;
    return this;
  }

  type(value: string): this {
    this.data['type'] = value;
    return this;
  }

  build(): ProviderCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as ProviderCreateRequest;
  }
}

export class ProviderPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  namespace(value: string): this {
    this.data['namespace'] = value;
    return this;
  }

  secret(value: string): this {
    this.data['secret'] = value;
    return this;
  }

  type(value: string): this {
    this.data['type'] = value;
    return this;
  }

  build(): ProviderPatchRequest {
    return this.data as ProviderPatchRequest;
  }
}
