// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: a700e964b95473caceb2974206b600566c98bac72daf731d9157564e26cf64a9
// Generated: 2026-07-15T18:51:55Z

import type { ObjectReference, ListMeta } from './base';

export type SessionMessage = ObjectReference & {
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type SessionMessageList = ListMeta & {
  items: SessionMessage[];
};

export type SessionMessageCreateRequest = {
  event_type?: string;
  payload?: string;
};

export type SessionMessagePatchRequest = {
};

export class SessionMessageBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  build(): SessionMessageCreateRequest {
    return this.data as SessionMessageCreateRequest;
  }
}

export class SessionMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  build(): SessionMessagePatchRequest {
    return this.data as SessionMessagePatchRequest;
  }
}
